name: fitness_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.6.3
  provider: ^6.0.0
  fl_chart: ^0.66.0
  intl: ^0.18.0
  image_picker: ^0.8.7+4
  flutter_local_notifications: 16.2.0
  timezone: ^0.9.4
  cached_network_image: ^3.3.1
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_avatar.png