// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcow3Pe2jtP4RH0kz-Qp3od22wWef6fBU',
    appId: '1:991867692599:web:fec504a763340ce5f681b2',
    messagingSenderId: '991867692599',
    projectId: 'fitness-tracker-app-aaf8b',
    authDomain: 'fitness-tracker-app-aaf8b.firebaseapp.com',
    storageBucket: 'fitness-tracker-app-aaf8b.firebasestorage.app',
    measurementId: 'G-7Z1YM3H588',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3B2WLW4j9QrCngyIx0CtfmBfAyvkak0',
    appId: '1:991867692599:android:d0323fbb9f72a934f681b2',
    messagingSenderId: '991867692599',
    projectId: 'fitness-tracker-app-aaf8b',
    storageBucket: 'fitness-tracker-app-aaf8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATwxTln56LxvmsSBDZwwlqaxFBGQX-RxI',
    appId: '1:991867692599:ios:7d53c6b44444aca0f681b2',
    messagingSenderId: '991867692599',
    projectId: 'fitness-tracker-app-aaf8b',
    storageBucket: 'fitness-tracker-app-aaf8b.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATwxTln56LxvmsSBDZwwlqaxFBGQX-RxI',
    appId: '1:991867692599:ios:7d53c6b44444aca0f681b2',
    messagingSenderId: '991867692599',
    projectId: 'fitness-tracker-app-aaf8b',
    storageBucket: 'fitness-tracker-app-aaf8b.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcow3Pe2jtP4RH0kz-Qp3od22wWef6fBU',
    appId: '1:991867692599:web:e1922f11a771e57cf681b2',
    messagingSenderId: '991867692599',
    projectId: 'fitness-tracker-app-aaf8b',
    authDomain: 'fitness-tracker-app-aaf8b.firebaseapp.com',
    storageBucket: 'fitness-tracker-app-aaf8b.firebasestorage.app',
    measurementId: 'G-8YT7D5GKX9',
  );
}
